# coding: utf-8

'''
Manually copy some content from cp_emoji.py
'''

chars = {
    "🍄": "mushroom,蘑菇",
    "🍄‍🟫": "brown_mushroom,棕色蕈菇",
    "🍅": "tomato,番茄",
    "🍆": "eggplant,茄子",
	"🍇": "grapes,葡萄",
    "🍈": "melon,瓜",
    "🍉": "watermelon,西瓜",
    "🍊": "tangerine,橘子",
    "🍋": "lemon,檸檬",
    "🍋‍🟩": "lime,萊姆",
    "🍌": "banana,香蕉",
    "🍍": "pineapple,鳳梨",
    "🍎": "red_apple,紅蘋果",
    "🍏": "green_apple,青蘋果",
    "🍐": "pear,梨子",    
    "🍒": "cherries,櫻桃",
    "🍓": "strawberry,草莓",
    "🍔": "hamburger,漢堡",
    "🍕": "pizza,披薩",
    "🍖": "meat_on_bone,排骨",
    "🍗": "poultry_leg,雞腿",
    "🍘": "rice_cracker,米果",
    "🍙": "rice_ball,飯糰",
    "🍚": "cooked_rice,米飯",
    "🍛": "curry_rice,咖哩飯",
    "🍜": "steaming_bowl,湯麵",
    "🍝": "spaghetti,義大利麵",
    "🍞": "bread,吐司",
    "🍟": "french_fries,薯條",
    "🍠": "roasted_sweet_potato,烤地瓜",
    "🍡": "dango,糥米丸子",
    "🍢": "oden,關東煮",
    "🍣": "sushi,壽司",
    "🍤": "fried_shrimp,天婦羅",
    "🍥": "fish_cake_with_swirl,魚板",
    "🍦": "soft_ice_cream,霜淇淋",
    "🍧": "shaved_ice,刨冰",
    "🍨": "ice_cream,冰淇淋",
    "🍩": "doughnut,甜甜圈",
    "🍪": "cookie,餅乾",
    "🍫": "chocolate_bar,巧克力",
    "🍬": "candy,糖",
    "🍭": "lollipop,棒棒糖",
    "🍮": "custard,卡士達",
    "🍯": "honey_pot,蜂蜜",
    "🍰": "shortcake,蛋糕",
    "🍱": "bento_box,便當",
    "🍲": "pot_of_food,火鍋",
    "🍳": "cooking,煎蛋",
    "🍴": "fork_and_knife,刀叉",
    "🍵": "teacup_without_handle,熱茶",
    "🍶": "sake,清酒",
    "🍷": "wine_glass,葡萄酒",
    "🍸": "cocktail_glass,雞尾酒",
    "🍹": "tropical_drink,熱帶水果飲料",
    "🍺": "beer_mug,啤酒",
    "🍻": "clinking_beer_mugs,乾杯吧",
    "🍼": "baby_bottle,奶瓶",
    "🍽": "fork_and_knife_with_plate,餐具",
    "🍾": "bottle_with_popping_cork,洋酒",
    "🍿": "popcorn,爆米花",
    "🎂": "birthday_cake,生日蛋糕",
    "🎃": "jack-o-lantern,南瓜燈",   
    "🥐": "croissant,可頌",
    "🥑": "avocado,酪梨",
    "🥒": "cucumber,小黃瓜",
    "🥓": "bacon,培根",
    "🥔": "potato,馬鈴薯",
    "🥕": "carrot,胡蘿蔔",
    "🥖": "baguette_bread,法國麵包",
    "🥗": "green_salad,生菜沙拉",
    "🥘": "shallow_pan_of_food,淺鍋料理",
    "🥙": "stuffed_flatbread,薄捲餅",
    "🥚": "egg,蛋",
    "🥛": "glass_of_milk,一杯牛奶",
    "🥜": "peanuts,花生",
    "🥝": "kiwi_fruit,奇異果",
    "🥞": "pancakes,鬆餅",
    "🥟": "dumpling,水餃",
    "🥠": "fortune_cookie,幸運餅乾",
    "🥡": "takeout_box,外帶餐盒",
    "🥢": "chopsticks,筷子",
    "🥣": "bowl_with_spoon,碗和湯匙",
    "🥤": "cup_with_straw,杯子和吸管",
    "🥥": "coconut,椰子",
    "🥦": "broccoli,花椰菜",
    "🥧": "pie,派",
    "🥨": "pretzel,蝴蝶餅",
    "🥩": "cut_of_meat,肉片",
    "🥪": "sandwich,三明治",
    "🥫": "canned_food,罐頭食品",
    "🥬": "leafy_green,綠葉蔬菜",
    "🥭": "mango,芒果",
    "🥮": "moon_cake,月餅",
    "🥯": "bagel,貝果",
    "🫐": "blueberries,藍莓",
    "🫑": "bell_pepper,甜椒",
    "🫒": "olive,橄欖",
    "🫓": "flatbread,麵餅",
    "🫔": "tamale,玉米粉蒸肉",
    "🫕": "fondue,涮製菜餚",
    "🫖": "teapot,茶壺",
    "🫗": "pouring_liquid,倒出液體",
    "🫘": "beans,豆子",
    "🫙": "jar,廣口瓶",
    "🫚": "ginger_root,薑",
    "🫛": "pea_pod,豌豆莢",
}
