APPNAME = app
OBJECTS = main.o
TARGET = $(OBJECTS)

CC = arm-linux-gnueabi-gcc-4.9
CXX = arm-linux-gnueabi-g++-4.9
CXXFLAGS = -O3 -Wall -std=gnu++11
#LDFLAGS = -lstdc++ -static-libstdc++
LDFLAGS = -lstdc++

all: $(TARGET)
	$(CXX) $(CXXFLAGS) $(OBJECTS) -o $(APPNAME) $(LDFLAGS)

main.o: main.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

clean:
	rm -rf *.o $(APPNAME)

