#!/bin/bash

#
# This script combines two images horizontally and
# vertically using ImageMagick. The sample images are
# generated by gen-text-images.sh.
#
# if montage more images, like 2x3 (3 rows, 2 columns),
#

function combine_horizontally() {
    local lhs=$1
    local rhs=$2
    local output_file=$3

    magick montage "$lhs" "$rhs" \
        -mode Concatenate -tile x1 "$output_file" # one row
    echo "Combined images into: '$output_file'"
}

function combine_vertically() {
    local lhs=$1
    local rhs=$2
    local output_file=$3

    magick montage "$lhs" "$rhs" \
        -mode Concatenate -tile x2 "$output_file" # two rows
    echo "Combined images into: '$output_file'"
}

lhs="sans.png"
rhs="serif.png"

if [ -e "$lhs" ] && [ -e "$rhs" ]; then
    combine_horizontally "$lhs" "$rhs" "c-horizontal.png"
    combine_vertically "$lhs" "$rhs" "c-vertical.png"
else
    echo "run gen-text-images.sh first to generate images."
    exit 1
fi
