/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -p chat_interface.h:chat_interface.cpp com.pega.rasmus.xml
 *
 * qdbusxml2cpp is Copyright (C) 2016 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef CHAT_INTERFACE_H
#define CHAT_INTERFACE_H

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface com.pega.rasmus
 */
class ComPegaRasmusInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "com.pega.rasmus"; }

public:
    ComPegaRasmusInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~ComPegaRasmusInterface();

public Q_SLOTS: // METHODS
Q_SIGNALS: // SIGNALS
    void action(const QString &nickname, const QString &text);
    void foobar(const QString &text);
    void message(const QString &nickname, const QString &text);
};

namespace com {
  namespace pega {
    typedef ::ComPegaRasmusInterface rasmus;
  }
}
#endif
