/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.18 from the
 * contents of TestMax.xs. Do not edit this file, edit TestMax.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "TestMax.xs"
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#include "ppport.h"


#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#line 22 "TestMax.c"

XS(XS_TestMax_Max); /* prototype to pass -Wmissing-prototypes */
XS(XS_TestMax_Max)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "TestMax::Max", "a, b");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	int	RETVAL;
	dXSTARG;
	int	a = (int)SvIV(ST(0));
	int	b = (int)SvIV(ST(1));
#line 12 "TestMax.xs"
        RETVAL = (a > b) ? a : b;
#line 42 "TestMax.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_TestMax); /* prototype to pass -Wmissing-prototypes */
XS(boot_TestMax)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    char* file = __FILE__;

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    XS_VERSION_BOOTCHECK ;

        newXS("TestMax::Max", XS_TestMax_Max, file);
    XSRETURN_YES;
}

