#
# Makefile
# just show some help messages
#

phony: help

help:
	@echo "help message while you run **make**"
	@echo "suggest:"
	@echo "  py run_example.py"
	@echo "  py goldbach_conj.py"

run:
	python run_example.py

