POLAR_SOURCES := \
    polarssl/library/aes.c \
    polarssl/library/aesni.c \
    polarssl/library/arc4.c \
    polarssl/library/asn1parse.c \
    polarssl/library/asn1write.c \
    polarssl/library/base64.c \
    polarssl/library/bignum.c \
    polarssl/library/blowfish.c \
    polarssl/library/camellia.c \
    polarssl/library/certs.c \
    polarssl/library/cipher.c \
    polarssl/library/cipher_wrap.c \
    polarssl/library/ctr_drbg.c \
    polarssl/library/debug.c \
    polarssl/library/des.c \
    polarssl/library/dhm.c \
    polarssl/library/ecdh.c \
    polarssl/library/ecdsa.c \
    polarssl/library/ecp.c \
    polarssl/library/ecp_curves.c \
    polarssl/library/entropy.c \
    polarssl/library/entropy_poll.c \
    polarssl/library/error.c \
    polarssl/library/gcm.c \
    polarssl/library/havege.c \
    polarssl/library/hmac_drbg.c \
    polarssl/library/md.c \
    polarssl/library/md2.c \
    polarssl/library/md4.c \
    polarssl/library/md5.c \
    polarssl/library/md_wrap.c \
    polarssl/library/memory_buffer_alloc.c \
    polarssl/library/net.c \
    polarssl/library/oid.c \
    polarssl/library/padlock.c \
    polarssl/library/pbkdf2.c \
    polarssl/library/pem.c \
    polarssl/library/pk.c \
    polarssl/library/pk_wrap.c \
    polarssl/library/pkcs11.c \
    polarssl/library/pkcs12.c \
    polarssl/library/pkcs5.c \
    polarssl/library/pkparse.c \
    polarssl/library/pkwrite.c \
    polarssl/library/platform.c \
    polarssl/library/ripemd160.c \
    polarssl/library/rsa.c \
    polarssl/library/sha1.c \
    polarssl/library/sha256.c \
    polarssl/library/sha512.c \
    polarssl/library/ssl_cache.c \
    polarssl/library/ssl_ciphersuites.c \
    polarssl/library/ssl_cli.c \
    polarssl/library/ssl_srv.c \
    polarssl/library/ssl_tls.c \
    polarssl/library/threading.c \
    polarssl/library/timing.c \
    polarssl/library/version.c \
    polarssl/library/version_features.c \
    polarssl/library/x509.c \
    polarssl/library/x509_create.c \
    polarssl/library/x509_crl.c \
    polarssl/library/x509_crt.c \
    polarssl/library/x509_csr.c \
    polarssl/library/x509write_crt.c \
    polarssl/library/x509write_csr.c \
    polarssl/library/xtea.c

