/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp radioctrl.xml -i radiocontrol.h -a radioadapter
 *
 * qdbusxml2cpp is Copyright (C) 2015 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "radioadapter.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class RadioControlAdaptor
 */

RadioControlAdaptor::RadioControlAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

RadioControlAdaptor::~RadioControlAdaptor()
{
    // destructor
}

QString RadioControlAdaptor::am_val2str(uint in0)
{
    // handle method call local.RadioControl.am_val2str
    QString out0;
    QMetaObject::invokeMethod(parent(), "am_val2str", Q_RETURN_ARG(QString, out0), Q_ARG(uint, in0));
    return out0;
}

void RadioControlAdaptor::disableRadio()
{
    // handle method call local.RadioControl.disableRadio
    QMetaObject::invokeMethod(parent(), "disableRadio");
}

void RadioControlAdaptor::dump_radio_info()
{
    // handle method call local.RadioControl.dump_radio_info
    QMetaObject::invokeMethod(parent(), "dump_radio_info");
}

void RadioControlAdaptor::enableRadio(bool onOff)
{
    // handle method call local.RadioControl.enableRadio
    QMetaObject::invokeMethod(parent(), "enableRadio", Q_ARG(bool, onOff));
}

void RadioControlAdaptor::finish()
{
    // handle method call local.RadioControl.finish
    QMetaObject::invokeMethod(parent(), "finish");
}

QString RadioControlAdaptor::fm_val2str(uint in0)
{
    // handle method call local.RadioControl.fm_val2str
    QString out0;
    QMetaObject::invokeMethod(parent(), "fm_val2str", Q_RETURN_ARG(QString, out0), Q_ARG(uint, in0));
    return out0;
}

void RadioControlAdaptor::onFinishWork()
{
    // handle method call local.RadioControl.onFinishWork
    QMetaObject::invokeMethod(parent(), "onFinishWork");
}

void RadioControlAdaptor::onFinished()
{
    // handle method call local.RadioControl.onFinished
    QMetaObject::invokeMethod(parent(), "onFinished");
}

void RadioControlAdaptor::readRadioInfo()
{
    // handle method call local.RadioControl.readRadioInfo
    QMetaObject::invokeMethod(parent(), "readRadioInfo");
}

void RadioControlAdaptor::seekRadioDown()
{
    // handle method call local.RadioControl.seekRadioDown
    QMetaObject::invokeMethod(parent(), "seekRadioDown");
}

void RadioControlAdaptor::seekRadioUp()
{
    // handle method call local.RadioControl.seekRadioUp
    QMetaObject::invokeMethod(parent(), "seekRadioUp");
}

void RadioControlAdaptor::setFreqval(uint in0, bool in1)
{
    // handle method call local.RadioControl.setFreqval
    QMetaObject::invokeMethod(parent(), "setFreqval", Q_ARG(uint, in0), Q_ARG(bool, in1));
}

void RadioControlAdaptor::setRadioVol(ushort vol)
{
    // handle method call local.RadioControl.setRadioVol
    QMetaObject::invokeMethod(parent(), "setRadioVol", Q_ARG(ushort, vol));
}

