# This is a TOML document

title = "TOML Example"

[owner]
name = "Tom Preston-Werner"
dob = 1979-05-27T07:32:00-08:00
comment = "You can \"quote\" me, name\tJos\u00E9\nLoc\tSF."

[database]
enabled = true
server = "192.168.1.1"
ports = [ 8000, 8001, 8002 ]
data = [ ["delta", "phi"], [3.14] ]
connection_max = 5000
temp_targets = { cpu = 79.5, case = 72.0 }
# will no line break within
comment = """\
  The quick brown \
  fox jumps over \
  the lazy dog.\
  """
path = 'c:\Users\nodejs\templates'
regex = '<\i\c*\s*>'
lines = '''
The first newline is
trimmed in raw strings.
All other whitespace
is preserved.
'''

  [servers.alpha]
  ip = "10.0.0.1"
  role = "frontend"

  [servers.beta]
  ip = "10.0.0.2"
  role = "backend"

[clients]
data = [ ["gamma", "delta"], [403, 404] ]
wtf = { 'odd' = [1,3,5,7,], 'even' = [2,4,6,8,] }

[values]
# integers
int1 = +99
int2 = 42
int3 = 0
int4 = -17

# hexadecimal with prefix `0x`
hex1 = 0xDEADBEEF
hex2 = 0xdeadbeef
hex3 = 0xdead_beef

# octal with prefix `0o`
oct1 = 0o01234567
oct2 = 0o755

# binary with prefix `0b`
bin1 = 0b11010110

# fractional
float1 = +1.0
float2 = 3.1415
float3 = -0.01

# exponent
float4 = 5e+22
float5 = 1e06
float6 = -2E-2

# both
float7 = 6.626e-34

# separators
float8 = 224_617.445_991_228

# infinity
infinite1 = inf # positive infinity
infinite2 = +inf # positive infinity
infinite3 = -inf # negative infinity

# not a number
not1 = nan
not2 = +nan
not3 = -nan

[dates]
# offset datetime
odt1 = 1979-05-27T07:32:00Z
odt2 = 1979-05-27T00:32:00-07:00
odt3 = 1979-05-27T00:32:00.999999-07:00

# local datetime
ldt1 = 1979-05-27T07:32:00
ldt2 = 1979-05-27T00:32:00.999999

# local date
ld1 = 1979-05-27

# local time
lt1 = 07:32:00
lt2 = 00:32:00.999999
