#!/usr/bin/perl

#
# extract strokes data from Unihan7.0.0
# Unihan_DictionaryLikeData.txt
#

sub main()
{
    my $iff = q(../../Unihan700/Unihan_DictionaryLikeData.txt);
    my $off = q(extract_ktotalstrokes.txt);
    my $cnt = 0;
    my $hit = 0;

    open my $ifh, $iff or die;
	open my $ofh, "> $off" or die;

    print $ofh "# generated by ext_stroke.pl\n";
    while (<$ifh>) {
        printf "%d / %d\r", $hit, $cnt;
		$cnt ++;
        next if ( m/^$/ );
        next if ( m/^#/ );
        # only extract U+0000 to U+FFFF
		if ( m/^(U\+[0-9a-fA-F]{4})\s+kTotalStrokes\s+(\d+)/ ) {
			#printf $ofh "$1    $2\n";
			printf $ofh $_;
			$hit ++;
			print $cnt,"\r";
		}
	}
    print "\n";
    close $ifh;
    close $ofh;
}

main;

