#!/usr/bin/perl

#
# Using Image::ExifTool to retrieve camera model
# from images in list file
#
# and then, use ana_model.pl to get a stat
#

use strict;
use Image::ExifTool qw(:Public);

my $total_count = 0;	# total files processed
my $result_count = 0;	# count if result exists

sub main
{
	my $result;
	my $in_file = $ARGV[0] || 'list.txt';
	my $out_file = "model.txt";

	my $fmt = q("%s","%s");	# format string for printf

	open FH, $in_file or die "cannot open file $in_file: $!\n";
	open OFH, ">", $out_file or die "cannot output to $out_file\n";

	printf STDERR "Input from: <%s>\nOutput to: <%s>\n", $in_file, $out_file;

	print OFH "#\n# Generated by ''$0''\n#\n";

	LINE:
	while (<FH>)  {
		s/\n//;
		next LINE if m/^#/ or m/^$/;
		$result = get_exif_info($_);
		if ($result)  {
			printf OFH $fmt, $_, $result;
			print OFH "\n";
			++ $result_count;
		}
		printf STDERR "%d/%d\r", $result_count, $total_count;
	}
	print STDERR "\n";

	close FH;
	close OFH;
}

sub get_exif_info()
{
	my $img_file = shift;
	if (not -f $img_file)  {
		print "<$img_file> not found\n";
		return "";
	}

	++ $total_count;
	my $info = ImageInfo($img_file);
	#
	# get more data filed for further need
	#
	my $model = $$info{'Model'};
	undef $info;

	return $model;
}

main;
