#!/usr/bin/perl

# gen cmd from txt

use strict;
use 5.010;
use Getopt::Std;

my %known = (
	testExponentParsing => 1,
	testNamedFloats => 1,
	testSuffixParsing => 1,
	testVerifierTyping => 1,
	test_valueOf_String1 => 1,
	test_valueOf_String2 => 1,
	testInspectSslAfterConnect => 1,
	testMeasureTextWithLongText => 1,
	testAccessAllowFileAccess => 1,
	testScrollTo => 1,
);
my $defile = 'failcase.txt';
my $prefix = './cts-tradefed ';	# default with prefix
my $magic = qr(nohead);
my $opath = '../cts403r2/android-cts/tools/';

sub help()
{
	print<<EOL;

Usage: $0 [-n] [filename]

-n	no prefix string [$prefix]

if no filename is specified, use default name [$defile]
if script name contains [$magic], no prefix would be used

EOL

}

sub main()
{
	my %myopt = ();
	getopts('e:nhi:o:', \%myopt);

	if ( $myopt{'h'} ) {
		help();
		return;
	}

	my $file;
	my $extra = "";
	my $ofile;

	if ( $myopt{'i'} ) {
		$file = $myopt{'i'};
	} else {
		$file = $defile;
	}

	if ( $myopt{'o'} ) {
		$ofile = $opath . $myopt{'o'};
	} else {
		$ofile = $opath . $file . '.sh';
	}
	# no prefix if option '-n', or script name with 'nohead'
	if ( $myopt{'n'} || ($0 =~ $magic) ) {
		$prefix = '';
	}

### start to output
	print "open $file...\noutput to $ofile...\n";
	open my $fh, $file or die "no such file?";
	open my $ofh, "> $ofile" or die;

	print $ofh "#!/bin/bash\n";
	printf $ofh "# generated by %s\n", $0;
	printf $ofh "# imported from %s\n", $file;
	if ( $myopt{'e'} ) {
		$extra = $myopt{'e'};
		printf $ofh "# with extra switch: %s\n", $extra;
	}
	print $ofh "\n";
	while (<$fh>) {
		if ( m/^(\S+) (\S+)/ ) {
			my ($cname, $mname) = ($1, $2);
			unless ( $known{$mname} )  {
				printf $ofh "%srun cts %s -c %s -m %s\n", $prefix, $extra, $cname, $mname;
			} else {
				#print STDERR "skip\n";
			}
		} else {
			printf $ofh "# %s", $_;
		}
	}
	close $fh;
	close $ofh;

	my $cmd = sprintf("chmod +x %s", $ofile);
	system $cmd;
}

main;

