#!/usr/bin/perl

# gen cmd from txt

use strict;
use 5.010;
use Getopt::Std;

my %known = (
	testExponentParsing => 1,
	testNamedFloats => 1,
	testSuffixParsing => 1,
	testVerifierTyping => 1,
	test_valueOf_String1 => 1,
	test_valueOf_String2 => 1,
	testInspectSslAfterConnect => 1,
	testMeasureTextWithLongText => 1,
	testAccessAllowFileAccess => 1,
	testScrollTo => 1,
);
my $defile = 'failcase.txt';
my $prefix = './cts-tradefed ';	# default with prefix
my $magic = qr(nohead);

sub help()
{
	print<<EOL;

Usage: $0 [-n] [filename]

-n	no prefix string [$prefix]

if no filename is specified, use default name [$defile]
if script name contains [$magic], no prefix would be used

EOL

}

sub main()
{
	my %myopt = ();
	getopts('nh', \%myopt);

	if ( $myopt{'h'} ) {
		help();
		return;
	}

	my $file = $ARGV[0] // $defile;

	# no prefix if option '-n', or script name with 'nohead'
	if ( $myopt{'n'} || ($0 =~ $magic) ) {
		$prefix = '';
	}

	#print "open $file...\n";
	open my $fh, $file or die "no such file?";
	say "#!/bin/bash";
	printf("# generated by %s\n\n", $0);
	while (<$fh>) {
		if ( m/^(\S+) (\S+)/ ) {
			my ($cname, $mname) = ($1, $2);
			unless ( $known{$mname} )  {
				printf("%srun cts -c %s -m %s\n", $prefix, $cname, $mname);
			} else {
				#print STDERR "skip\n";
			}
		} else {
			printf("# %s", $_);
		}
	}
	close $fh;
}

main;

